apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mts-frontend
    spec:
      containers:
      - name: frontend
        image: denniseffing/oasp-mts-angular:nightly
        ports:
        - containerPort: 80

---
# Service
kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: mts-frontend
  type: ClusterIP
  ports:
  - port: 80
    name: http