apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-booking-order
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mts-booking-order
    spec:
      containers:
      - name: java
        image: denniseffing/mts-booking-order:1.0.0
        ports:
        - containerPort: 8081

---
# Service
kind: Service
apiVersion: v1
metadata:
  name: mts-booking-order
spec:
  selector:
    app: mts-booking-order
  type: ClusterIP
  ports:
  - port:  8081
    name: http