#################################################################################
# MyThaiStar Booking Order deployment
#################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: booking-order-service-account
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-booking-order
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mts-booking-order
    spec:
      serviceAccountName: booking-order-service-account
      containers:
      - name: booking-order
        image: denniseffing/mts-booking-order:1.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 200
          periodSeconds: 120
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 200
          periodSeconds: 120
---