apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-auth"
spec:
  targets:
  - name: mts-booking-order
  peers:
  - mtls: {}
  origins:
  - jwt:
      issuer: https://mythaistar.eu.auth0.com/
      jwksUri: https://mythaistar.eu.auth0.com/.well-known/jwks.json
  principalBinding: USE_ORIGIN
---