#################################################################################
# MyThaiStar Booking Order service
#################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mts-booking-order
  labels:
    app: mts-booking-order
spec:
  type: ClusterIP
  ports:
  - port:  8081
    targetPort: 8081
    name: http
  selector:
    app: mts-booking-order
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-booking-order
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mts-booking-order
    spec:
      containers:
      - name: booking-order
        image: denniseffing/mts-booking-order:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
---