#################################################################################
# MyThaiStar Booking Order service
#################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mts-booking-order
  labels:
    app: mts-booking-order
spec:
  type: ClusterIP
  ports:
  - port:  8081
    targetPort: 8081
    name: http
  selector:
    app: mts-booking-order
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-booking-order
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mts-booking-order
    spec:
      containers:
      - name: booking-order
        image: denniseffing/mts-booking-order:1.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 5
---
#################################################################################
# MyThaiStar Dishes service
#################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mts-dishes
  labels:
    app: mts-dishes
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: mts-dishes
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-dishes-v1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mts-dishes
        version: v1
    spec:
      containers:
      - name: dishes
        image: denniseffing/mts-dishes:1.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
#################################################################################
# MyThaiStar Frontend service
#################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mts-frontend
  labels:
    app: mts-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: mts-frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mts-frontend
    spec:
      containers:
      - name: frontend
        image: denniseffing/mts-frontend:1.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---