#################################################################################
# Activate Role Based Access Control
# - RBAC is deny by default!
#################################################################################
apiVersion: "rbac.istio.io/v1alpha1"
kind: RbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'
  inclusion:
    namespaces: ["default"]