#################################################################################
# Circuit breaker configuration for dishes service
# Triggers when:
# - More than 100 HTTP requests are pending
# - More than two concurrent requests are being made for a connection (HTTP 2)
# - The service returns two consecutive errors
# Instance is ejected for three minutes and consecutive error count is checked every second.
# The load balancing pool of the dishes service consists of two instances (v1 and v2) but only one is ejected at the same time.
#################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mts-dishes-cb
spec:
  host: mts-dishes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 2
    outlierDetection:
      consecutiveErrors: 2
      interval: 1s
      baseEjectionTime: 3m
      maxEjectionPercent: 80
---
#################################################################################
# Scale dishes service down to only one instance
# For demonstrating purposes
#################################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-dishes-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mts-dishes
        version: v1
    spec:
      containers:
      - name: dishes
        image: denniseffing/mts-dishes:1.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
#################################################################################
# Deploy v2 of dishes service that contains occasional failures
# For demonstrating purposes
#################################################################################
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-dishes-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mts-dishes
        version: v2
    spec:
      containers:
      - name: dishes
        image: denniseffing/mts-dishes:2.0-with-failures
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5