apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mts-dishes-cb
spec:
  host: mts-dishes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      http:
        http2MaxRequests: 100
        maxRequestsPerConnection: 2
    outlierDetection:
      consecutiveErrors: 2
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 70
---
#################################################################################
# Istio virtual service configuration with injected outages for dishes service
# This is needed for triggering the circuit breaker
#################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mts-routes
spec:
  hosts:
  - mts.local
  - mts.local:31380
  - mts.local:31390
  - mts-dishes.default.svc.cluster.local
  gateways:
  - mesh
  - mts-gateway
  http:
  - match:
    - uri:
        prefix: /api/services/rest/dishmanagement/
      headers:
        baggage-username: 
          exact: fault.injection
    - sourceLabels:
        app: mts-booking-order
      headers:
        baggage-username: 
          exact: fault.injection
    fault:
      abort:
        httpStatus: 500
        percent: 10
    rewrite:
      uri: /
    route:
    - destination:
        host: mts-dishes.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /api/services/rest/dishmanagement/
    rewrite:
      uri: /
    route:
    - destination:
        host: mts-dishes.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /api
    rewrite:
      uri: /mythaistar
    route:
    - destination:
        host: mts-booking-order.default.svc.cluster.local
        port:
          number: 8081
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: mts-frontend.default.svc.cluster.local
        port:
          number: 80