#################################################################################
# Istio virtual service configuration with timeout for booking order service
#################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mts-routes
spec:
  hosts:
  - mts.local
  - mts.local:31380
  - mts.local:31390
  gateways:
  - mts-gateway
  http:
  - match:
    - uri:
        prefix: /api/services/rest/dishmanagement/   
    rewrite:
      uri: /
    route:
    - destination:
        host: mts-dishes.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: /api
    rewrite:
      uri: /mythaistar
    route:
    - destination:
        host: mts-booking-order.default.svc.cluster.local
        port:
          number: 8081
    timeout: 3s
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: mts-frontend.default.svc.cluster.local
        port:
          number: 80
---
#################################################################################
# Istio virtual service configuration with injected delay for requests to dishes
# service
#################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mts-dishes-routing
spec:
  hosts:
  - mts-dishes.default.svc.cluster.local
  http:
  - match: 
    - sourceLabels:
        app: mts-booking-order
      headers:
        baggage-username:
          exact: fault.injection
    fault:
      delay:
        fixedDelay: 200ms
        percent: 100
    route:
    - destination:
        host: mts-dishes.default.svc.cluster.local
        port:
          number: 80
  - match:
    - sourceLabels:
        app: mts-booking-order
    route:
    - destination:
        host: mts-dishes.default.svc.cluster.local
        port:
          number: 80
    