apiVersion: v1
kind: Service
metadata:
  name: mts-dishes-api
spec:
  selector:
    app: mts-dishes
    tier: api
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-dishes-api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mts-dishes
      tier: api
      version: v1
  template:
    metadata:
      labels:
        app: mts-dishes
        tier: api
        version: v1
    spec:
      containers:
      - name: dishes
        image: denniseffing/mts-dishes:1.2
        ports:
        - containerPort: 8080