#################################################################################
# MyThaiStar Booking Order service
#################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mts-booking-order
  labels:
    app: mts-booking-order
spec:
  type: ClusterIP
  ports:
  - port:  8081
    targetPort: 8081
    name: http
  selector:
    app: mts-booking-order
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-booking-order
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mts-booking-order
    spec:
      containers:
      - name: booking-order
        image: denniseffing/mts-booking-order:1.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
---
#################################################################################
# MyThaiStar Dishes service
#################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mts-dishes
  labels:
    app: mts-dishes
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: mts-dishes
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-dishes-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mts-dishes
        version: v1
    spec:
      containers:
      - name: dishes
        image: denniseffing/mts-dishes:1.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-dishes-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mts-dishes
        version: v2
    spec:
      containers:
      - name: dishes
        image: denniseffing/mts-dishes:1.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
#################################################################################
# MyThaiStar Frontend service
#################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mts-frontend
  labels:
    app: mts-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: mts-frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mts-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mts-frontend
    spec:
      containers:
      - name: frontend
        image: denniseffing/oasp-mts-angular:nightly
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---